(define (pt-element n k) 
  (cond ((< n 0) 0)
        ((< k 0) 0)
        ((> k n) 0)
        ((= k 0) 1)
        ((= n 0) 1)
        ((= n 1) 1)
        (else (+ (pt-element (- n 1) (- k 1))
                 (pt-element (- n 1) k)))))

(define (pt n)
  (define (iter n k)
    (cond ((< k 0) ())
          (else (cons (pt-element n k) 
                      (iter n (- k 1))))))
  (iter n n))