#!/bin/bash
# Bash completions

# Requires bash-completion package
if [ -f /run/current-system/sw/share/bash-completion/bash_completion ]; then
  source /run/current-system/sw/share/bash-completion/bash_completion
fi

if [ -f /run/current-system/sw/bin/complete_alias ]; then
  source /run/current-system/sw/bin/complete_alias
fi

# gopass
source <(gopass completion bash)

# kubectl
source <(kubectl completion bash)
