#!/usr/bin/env bash
# Setup fzf autocompletion and key bindings

if [[ $(uname -s) == 'Darwin' ]]; then
  if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
    export PATH="$PATH:/usr/local/opt/fzf/bin"
  fi

  source "/usr/local/opt/fzf/shell/key-bindings.bash"
else
  [ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash
fi
