#!/usr/bin/env bash
# Setup fzf autocompletion and key bindings
if command -v fzf-share >/dev/null; then
  # shellcheck disable=1091
  source "$(fzf-share)"/key-bindings.bash
  # shellcheck disable=1091
  source "$(fzf-share)"/completion.bash
fi

if command -v rg >/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --nocolor -g ""'
fi
