#!/bin/bash
# Bash variables

# Add ~/bin to PATH
export PATH=$HOME/bin:$PATH

# Use vim as default editor
export EDITOR=vim

# Disable homebrew analytics collection
export HOMEBREW_NO_ANALYTICS=1

# Set environment file location for ssh-agent configuration on login
export SSH_ENV="$HOME/.ssh/environment"

# Set KUBECONFIG to source ODC and Context k8s configs.
export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/us-phx-a

# Prevent Google logging go mod requests.
export GOPRIVATE='*.oracledatacloud.com,gs/*'
export GOPROXY='off'

# Alacritty terminal compatibility.
export TERM=xterm-256color

# GPG TTY
export GPG_TTY=$(tty)
