#!/bin/bash
# Bash variables

# Add ~/bin to PATH
export PATH=$HOME/bin:$PATH

# Use vim as default editor
export EDITOR="emacs -nw"

# Disable homebrew analytics collection
export HOMEBREW_NO_ANALYTICS=1

# Set environment file location for ssh-agent configuration on login
export SSH_ENV="$HOME/.ssh/environment"

# Alacritty terminal compatibility.
export TERM=xterm-256color

# GPG TTY
export GPG_TTY=$(tty)
